
ps:
	iverilog -g2012 -o pixelSensor -c pixelSensor.fl
	vvp -n pixelSensor

psfsm:
	iverilog -g2012 -o pixelSensorFsm -c pixelSensorFsm.fl
	vvp -n pixelSensorFsm

sm:
	iverilog -g2012 -o pixelTop -c pixelTop.fl
	vvp -n pixelTop


ysfsm: synth
	dot pixelSensorFsm.dot -Tpng > pixelSensorFsm.png

synth:
	yosys pixelSensorFsm.ys

synth2:
	yosys pixelsensor.ys


test: ps psfsm synth
